export const logos = [
  { src: "/images/logos/01.svg", alt: "Idea" },
  { src: "/images/logos/02.svg", alt: "Direcional engenharia" },
  { src: "/images/logos/03.svg", alt: "Volvo" },
  { src: "/images/logos/04.svg", alt: "BMW" },
  { src: "/images/logos/05.svg", alt: "Tim" },
  { src: "/images/logos/06.svg", alt: "Even" },
  { src: "/images/logos/07.svg", alt: "Tha engenharia" },
  { src: "/images/logos/08.svg", alt: "Construcamp" },
  { src: "/images/logos/09.svg", alt: "Athie" },
  { src: "/images/logos/10.svg", alt: "R. Yazbek" },
  { src: "/images/logos/11.svg", alt: "Cyrela" },
  { src: "/images/logos/12.svg", alt: "Rac engenharia" },
  { src: "/images/logos/13.svg", alt: "MPD" },
  { src: "/images/logos/01.svg", alt: "Idea" },
  { src: "/images/logos/02.svg", alt: "Direcional engenharia" },
  { src: "/images/logos/03.svg", alt: "Volvo" },
  { src: "/images/logos/04.svg", alt: "BMW" },
  { src: "/images/logos/05.svg", alt: "Tim" },
  { src: "/images/logos/06.svg", alt: "Even" },
  { src: "/images/logos/07.svg", alt: "Tha engenharia" },
  { src: "/images/logos/08.svg", alt: "Construcamp" },
  { src: "/images/logos/09.svg", alt: "Athie" },
  { src: "/images/logos/10.svg", alt: "R. Yazbek" },
  { src: "/images/logos/11.svg", alt: "Cyrela" },
  { src: "/images/logos/12.svg", alt: "Rac engenharia" },
  { src: "/images/logos/13.svg", alt: "MPD" },
];
